---
- name: enable sudo
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  tasks:
    - name: Enable full sudo access
      become: yes
      become_user: root
      lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: EOF
        line: '{{item.Line}}'
        validate: '/usr/sbin/visudo -cf %s'
      with_items:
        - { Line: '# Full access for setup' }
        - { Line: 'ansible ALL=(ALL) NOPASSWD: ALL' }
        - { Line: '# APT access' }
        - { Line: 'ansible ALL=(root) NOPASSWD: /usr/bin/apt-get update' }
        - { Line: 'ansible ALL=(root) NOPASSWD: /usr/bin/apt-get upgrade -y' }
        - { Line: 'ansible ALL=(root) NOPASSWD: /usr/bin/apt-get autoclean' }
        - { Line: 'ansible ALL=(root) NOPASSWD: /usr/bin/apt-get autoremove -y' }
