---
- name: Download All GPG Keys
  hosts: initial
  become: yes
  tasks:
    - name: install gnupg1
      apt:
        update_cache: yes
        name: gnupg1
    - name: install apt-transport-https
      apt:
        update_cache: yes
        name: apt-transport-https
    - name: install dirmngr
      apt:
        update_cache: yes
        name: dirmngr
    - name: Download Influx GPG key
      get_url:
        url: https://repos.influxdata.com/influxdb.key
        dest: /home/ansible/influxdb.gpg
