---
- name: Harden SSH
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  tasks:
    - name: Disable Root Login
      become: yes
      become_user: root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin\s[a-z\-A-Z]+'
        line: 'PermitRootLogin no'
        state: present
    - name: Disable password login
      become: yes
      become_user: root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication\syes'
        line: 'PasswordAuthentication no'
        state: present
    - name: Restart SSH
      become: yes
      become_user: root
      systemd:
        name: ssh
        state: restarted
