---
- name: initial-setup
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  become: yes
  tasks:
    - name: Set timezone
      timezone:
        name: America/New_York
    - name: APT Update and Upgrade
      apt:
        update_cache: yes
        upgrade: yes
        autoclean: yes
        autoremove: yes
    - name: Add my user account
      user:
        name: nick
        groups: sudo
        append: yes
    - name: Add ansible account
      user:
        name: ansible
        groups: sudo
        append: yes
