---
- name: initial-setup
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  tasks:
    - name: Set timezone
      become: yes
      become_user: root
      timezone:
        name: America/New_York
    - name: APT Update
      become: yes
      become_user: root
      apt:
        update_cache: yes
    - name: APT Upgrade
      become: yes
      become_user: root
      apt:
        name: "*"
        state: latest
        autoclean: yes
        autoremove: yes
