---
- name: initial-setup
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  tasks:
    - name: Set timezone
      become: yes
      become_user: root
      timezone:
        name: America/New_York
    - name: APT Update and upgrade
      become: yes
      become_user: root
      apt:
        update_cache: yes
        name: "*"
        state: latest
