---
- name: initial-setup
  hosts: initial # remember to setup /etc/ansible/hosts to the host to be setup
  tasks:
    - name: Set timezone
      command: sudo timedatectl set-timezone America/New_York