---
- name: Telegraf install
  hosts: initial
  become: yes
  tasks:
    - name: Add InfluxDB repository
      apt_repository:
        repo: ddeb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main
        state: present
        filename: influxdb
    - name: Telegraf Install
      apt:
        update_cache: yes
        name: telegraf
    - name: Enable service Telegraf and ensure it is not masked
      systemd:
        name: telegraf
        enabled: yes
        masked: no
    - name: Start service Telegraf
      systemd:
        name: telegraf
        state: started
