---
- name: Kali install
  hosts: kalipi
  become: yes
  tasks:
    - name: Add Kali repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali kali-rolling main contrib non-free
        state: present
        filename: kali
    - name: Kali core Install
      apt:
        update_cache: yes
        name: kali-linux-core
    - name: Kali headless Install
      apt:
        update_cache: yes
        name: kali-linux-headless
    - name: Kali arm Install
      apt:
        update_cache: yes
        name: kali-linux-arm
    - name: Kali top 10 tools Install
      apt:
        update_cache: yes
        name: kali-tools-top10
    - name: Create a python symbolic link
      file:
        src: /usr/bin/python2
        dest: /usr/bin/python2
        owner: root
        group: root
        state: link
