---
- name: Kali Pi setup
  hosts: kalipi
  become: yes
  tasks:
    - name: Set Hostname
      hostname:
        name: kalipi
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1 kalipi'
    - name: disable WiFi
      lineinfile:
        path: /boot/config.txt
        state: present
        insertafter: EOF
        line: 'dtoverlay=disable-wifi'
    - name: Reboot
      reboot:
