---
- name: Grafana install
  hosts: monitorpi
  tasks:
    - name: Download GPG key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /home/ansible/grafana.gpg
#        install must be ran manually as root user
#    - name: Install GPG key
#      become: yes
#      become_user: root
#      command: gpg --dearmor < /home/ansible/grafana.gpg > /usr/share/keyrings/grafana-archive-keyring.gpg
    - name: Add Grafana repository
      become: yes
      become_user: root
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
    - name: Grafana Install
      become: yes
      become_user: root
      apt:
        update_cache: yes
        name: grafana
    - name: Enable service Grafana and ensure it is not masked
      systemd:
        name: grafana-server
        enabled: yes
        masked: no
    - name: Start service Grafana
      systemd:
        name: grafana-server
        state: started
