---
- name: Grafana install
  hosts: monitorpi
  become: yes
  tasks:
    - name: Add Grafana repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
    - name: Grafana Install
      apt:
        update_cache: yes
        name: grafana
    - name: Enable service Grafana
      systemd:
        name: grafana-server
        enabled: yes
    - name: Start service Grafana
      systemd:
        name: grafana-server
        state: started
