---
- name: InfluxDB install
  hosts: monitorpi
  become: yes
  tasks:
    - name: Add InfluxDB repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/influxdb-archive-keyring.gpg] https://repos.influxdata.com/debian buster stable
        state: present
        filename: influxdb
    - name: InfluxDB Install
      apt:
        update_cache: yes
        name: influxdb
    - name: Enable service InfluxDB and ensure it is not masked
      systemd:
        name: influxdb
        enabled: yes
        masked: no
    - name: Start service InfluxDB
      systemd:
        name: influxdb
        state: started
    - name: Python3 InfluxDB Install
      apt:
        update_cache: yes
        name: python3-influxdb
