---
- name: Outage Detector install
  hosts: monitorpi
  become: yes
  tasks:
    - name: Python3 vitual env Install
      apt:
        update_cache: yes
        name: python3-venv
    - name: Create Outage Detector directory
      file:
        path: /opt/outageDetector
        state: directory
        mode: '0770'
        owner: monitor
        group: monitor
    - name: Create Cron detect job
      cron:
        name: "Automate outagedetector detect script"
        minute: "*/1"
        user: monitor
        job: "/opt/outageDetector/outageDetector/bin/python3 /opt/outageDetector/outageDetector/bin/outage_detector --run scheduled --notify notification"
    - name: Create Cron reboot job
      cron:
        name: "Automate outagedetector reboot script"
        special_time: reboot
        user: monitor
        job: "/opt/outageDetector/outageDetector/bin/python3 /opt/outageDetector/outageDetector/bin/outage_detector --run boot --notify notification"
