---
- name: Monitor Pi setup
  hosts: monitorpi
  become: yes
  tasks:
    - name: Set Hostname
      hostname:
        name: monitorpi
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1 monitorpi'
    - name: disable WiFi
      lineinfile:
        path: /boot/config.txt
        state: present
        insertafter: EOF
        line: 'dtoverlay=pi3-disable-wifi'
    - name: disable Bluetooth service
      command: systemctl disable hciuart
    - name: Add my user account
      user:
        name: monitor
        groups: sudo
        append: yes
    - name: Reboot
      reboot:
