---
- name: Speedtest install
  hosts: monitorpi
  become: yes
  tasks:
    - name: Add Speedtest repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/speedtest-cli-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/debian/ buster main
        state: present
        filename: speedtest
    - name: Speedtest Install
      apt:
        update_cache: yes
        name: speedtest
    - name: Create Speedtest directory
      file:
        path: /opt/speedtest
        state: directory
        mode: '0770'
        owner: monitor
        group: monitor
    - name: Create Cron job
      cron:
        name: "Automate speedtest script"
        minute: "0"
        user: monitor
        job: "python3 /opt/speedtest/speedtest.py"
