---
- name: Telegraf install
  hosts: monitorpi
  become: yes
  tasks:
    - name: Download GPG key
      get_url:
        url: https://repos.influxdata.com/influxdb.key
        dest: /home/ansible/influxdb.gpg
#        install must be ran manually as root user
#    - name: Install GPG key
#      command: gpg --dearmor < /home/ansible/influxdb.gpg > /usr/share/keyrings/influxdb-archive-keyring.gpg
    - name: Add InfluxDB repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/influxdb-archive-keyring.gpg] https://repos.influxdata.com/debian buster stable
        state: present
        filename: influxdb
    - name: Telegraf Install
      apt:
        update_cache: yes
        name: telegraf
    - name: Enable service Telegraf and ensure it is not masked
      systemd:
        name: telegraf
        enabled: yes
        masked: no
    - name: Start service Telegraf
      systemd:
        name: telegraf
        state: started
