---
- name: Tilt setup
  hosts: monitorpi
  tasks:
    - name: Add tilt account
      become: yes
      become_user: root
      user:
        name: tiltUser
        groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,spi,i2c,gpio
        append: yes
    - name: Install required packages
      become: yes
      become_user: root
      apt:
        update_cache: yes
        name: python3-distutils
