---
- name: Cloudflare DDNS Updater Install
  hosts: dns
  become: yes
  tasks:
    - name: Git Install
      apt:
        update_cache: yes
        name: git
    - name: Clone repository
      git:
        repo: https://github.com/K0p1-Git/cloudflare-ddns-updater.git
        dest: /opt/cloudflare-ddns-updater
    - name: Create Cron job
      cron:
        name: "Automate DDNS Updater"
        minute: "*/1"
        user: root
        job: "/bin/bash /opt/cloudflare-ddns-updater/cloudflare.sh"
