---
- name: Cloudflare DDNS Updater Install
  hosts: dns
  tasks:
    - name: Clone repository
      become: yes
      become_user: root
      git:
        repo: https://github.com/K0p1-Git/cloudflare-ddns-updater.git
        dest: /opt/cloudflare-ddns-updater
