---
- name: UniFi Controller MongoDB install
  hosts: unificontrollerpi
  tasks:
    - name: Add MongoDB GPG trusted key
      become: yes
      become_user: root
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present
    - name: Add MongoDB repository
      become: yes
      become_user: root
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main
        state: present
        filename: mongo.list
    - name: Mongo Install
      become: yes
      become_user: root
      apt:
        update_cache: yes
        name: mongodb-org
    - name: Start Mongo Service
      become: yes
      become_user: root
      systemd:
        name: mongod
        state: started
