---
- name: UniFi Controller required dependencies install
  hosts: unificontrollerpi
  tasks:
    - name: Add Oracle Java GPG trusted key
      command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
    - name: Add Oracle Java source list
      command: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/webupd8team-java.list
    - name: Add Oracle Java source list
      command: echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list.d/webupd8team-java.list
    - name: APT Update
      command: sudo apt-get update
    - name: APT install required dependency packages
      command: sudo apt-get install ca-certificates apt-transport-https oracle-java8-installer -y
