---
- name: UniFi Controller required dependencies install
  hosts: unificontrollerpi
  tasks:
    - name: APT Update
      command: sudo apt-get update
    - name: APT install required dependency packages
      command: sudo apt-get install ca-certificates apt-transport-https default-jre gnupg -y
