---
- name: UniFi Controller required dependencies install
  hosts: unificontrollerpi
  become: yes
  tasks:
    - name: Install CA Certificates
      apt:
        update_cache: yes
        name: ca-certificates
    - name: Install APT transport HTTPS
      apt:
        name: apt-transport-https
    - name: Install Java Runtime
      apt:
        name: openjdk-8-jre-headless
    - name: Install JSVC
      apt:
        name: jsvc
    - name: Install Java Libcommons daemon
      apt:
        name: libcommons-daemon-java
    - name: Install Haveged
      apt:
        name: haveged
    - name: Install RNG Tools
      apt:
        name: rng-tools
    - name: Update RNG Tools Config file
      lineinfile:
        path: /etc/default/rng-tools-debian
        regexp: '^#HRNGDEVICE=\/dev\/hwrng'
        line: 'HRNGDEVICE=/dev/hwrng'
    - name: Restart RNG Tools
      systemd:
        name: rng-tools
        state: restarted
    - name: Add MongoDB repository
      apt_repository:
        repo: deb http://archive.raspbian.org/raspbian stretch main contrib non-free rpi
        state: present
        filename: mongodb
    - name: Install MongoDB Server
      apt:
        name: mongodb-server
    - name: Install MongoDB Client
      apt:
        name: mongodb-clients
