---
- name: UniFi Controller Pi setup
  hosts: unificontrollerpi
  become: yes
  tasks:
    - name: Set Hostname
      hostname:
        name: controllerpi
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1 controllerpi'
    - name: disable WiFi
      lineinfile:
        path: /boot/config.txt
        state: present
        insertafter: EOF
        line: 'dtoverlay=pi3-disable-wifi'
    - name: disable Bluetooth
      lineinfile:
        path: /boot/config.txt
        state: present
        insertafter: EOF
        line: 'dtoverlay=pi3-disable-bt'
    - name: disable Bluetooth service
      command: systemctl disable hciuart
    - name: Reboot
      reboot:
