---
- name: apt-updates
  hosts: pis
  tasks:
    - name: Update packages
      become: yes
      become_user: root
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
